# fly.toml app configuration file generated for lobe-chat-client-test-2 on 2025-07-19T00:59:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lobe-chat-client-test-2'
primary_region = 'syd'

[build]
  
[deploy]

[http_service]
  internal_port = 3210
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '4096mb'
  cpu_kind = 'shared'
  cpus = 2
